import os
import random
from pyedflib import highlevel

# Root directory where S001, S002, ..., S109 are stored
root_dir = "backend/app/data/raw/files"

# Example random names
names = [
    "Alice", "Bob", "Charlie", "Diana", "Evelyn", "Frank", "Grace", "Hannah", "Ivan", "Julia",
    "Kevin", "Luna", "Michael", "Nina", "Oscar", "Paula", "Quinn", "Ryan", "Sophia", "Tom",
    "Uma", "Victor", "Wendy", "Xavier", "Yara", "Zane"
]

# Seed to make randomness reproducible (optional)
random.seed(42)

for subj in sorted(os.listdir(root_dir)):
    subj_dir = os.path.join(root_dir, subj)
    if not os.path.isdir(subj_dir):
        continue

    # Tạo random name và code CHO CẢ SUBJECT
    random_name = random.choice(names)
    random_code = f"S{random.randint(1, 999):03d}"

    # pick all EDF files in this subject (ignore .event)
    edfs = [
        f for f in os.listdir(subj_dir)
        if f.lower().endswith(".edf") and not f.lower().endswith(".event")
    ]
    if not edfs:
        continue

    print(f"\n🔁 Subject {subj}: assigned name '{random_name}' (code {random_code})")

    for edf_file in edfs:
        edf_path = os.path.join(subj_dir, edf_file)

        # Read EDF
        signals, signal_headers, header = highlevel.read_edf(edf_path)

        # Update header fields (this metadata will be saved permanently)
        header["patientname"] = random_name
        header["patientcode"] = random_code
        header["recording_additional"] = f"EEG from {random_name}"
        header["patient_additional"] = "Generated by random-name script"

        # Overwrite the same file (⚠️ no backup!)
        highlevel.write_edf(edf_path, signals, signal_headers, header)
        print(f"   [OVERWRITTEN] {edf_file}")
