version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    env_file:
      - .env
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: backend
    command: uvicorn app.main:socket_app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - rabbitmq
    volumes:
      - .:/app                # mount toàn bộ project
      - ./app/data/uploads:/app/app/data/uploads  # share folder uploads

  worker:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: worker
    command: celery -A celery_app.celery_app worker --loglevel=info --pool=solo -Q eeg
    env_file:
      - .env
    depends_on:
      - rabbitmq
    volumes:
      - .:/app
      - ./app/data/uploads:/app/app/data/uploads  # share folder uploads

volumes:
  rabbitmq_data:
